### ISSUE TITLE
send-event ignores DSN query string parameters

### ISSUE THREAD

**Issue by ghadishayban** [getsentry/sentry-clj#13]
Because sentry-clj calls `(Sentry/capture Event)` [1]  rather than `(Sentry/capture EventBuilder)` [2] on the underlying Java library, `release` and `environment` are always `null`.

We set the release in the sentry DSN as a query parameter. The clojure lib calls (map->Event), which sets all the unspecified params on the Event to nil, and this overrides the DSN parameters

[1] https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/SentryClient.java#L126-L143
[2] https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/SentryClient.java#L150-L156

**Comment by bretthoerner** [comment]
Crap, good catch! I'll try to get to this soon, or PRs definitely welcome. :)

**Comment by bretthoerner** [comment]
I changed it to capture the EventBuilder instead, this should fix it. Let me know, thanks!
