### ISSUE TITLE
Event X make different event Y instead in Sentry

### ISSUE THREAD

**Issue by kwladyka** [getsentry/sentry-clj#17]
It is very werid bug and I have big problem how to report it, because I can't paste `:throwable`, because it contains data, which I can't public.

**I send event X, but Sentry report on slack and show in panel only last event Y, which has totally different `:throwable` and is different event from the past.** Event X doesn't exist in Sentry, at least I can't search it. So in magic way event X is transformed into event Y and I have no idea what is happening. In 100% times the same X always produce the same Y.

Code below is not really important, but I paste it anyway.
```clojure
(sentry/send-event (merge sentry-base
                          {:level (get timbre->sentry-levels level)
                           :fingerprint (when (or error-message (force msg_))
                                          (->> (set [?ns-str error-message (force msg_)])
                                               (clojure.set/union causes)
                                               (remove #(= "" %))
                                               (remove nil?)))
                           :logger ?ns-str
                           :extra context
                           :message (not-empty (force msg_))
                           :throwable ?err}))
```

For debug reasons I save this map above to `foo` atom to be 100% sure what I am sending to Sentry.

`(sentry/send-event @foo)` return `3de6efe8c7564fbe86a489d3c8de7ae8`.
Slack bot shows me a link to new event `aae12a66f8e84edfac45a18958bfbfa8`. It is also the only one event created in Sentry panel.

When I use `3de6efe8c7564fbe86a489d3c8de7ae8` (right event X) in Sentry search panel it shows me 1 position, when I click on it I see `aae12a66f8e84edfac45a18958bfbfa8` (wrong event Y).
I am going to open "Events" and try to search here again by `3de6efe8c7564fbe86a489d3c8de7ae8` and I see "Sorry, no events match your search query.".

It blows my mind. I guess it could be Sentry bug in engine, but I report it here, because I use this library to send events. At least I don't know better place.

My username in Sentry is `kwladyka`.

**Comment by bretthoerner** [comment]
Is the creation of the event reproducible? Like could you cause it happen again but send it to a dummy server that will just print the contents of the body, so that we can inspect and verify the JSON payload that the SDK is sending?

For example I use something simple like,

```
# cat read-payload.py 
import json, sys, gzip, StringIO

request = sys.stdin.read()
headers, payload = request.split('\r\n\r\n', 1)

sys.stdout.write(headers + "\n\n")

payload = gzip.GzipFile(fileobj=StringIO.StringIO(payload), mode='rb').read()
result = json.loads(payload)

sys.stdout.write(json.dumps(result, indent=2))
```

Run dummy server: `netcat -l 9999 | python2 read-payload.py`

Send an event to the dummy DSN (this is a Java example): `SENTRY_DSN="http://foo@localhost:9999/1?async=false" mvn clean compile exec:java`

**Comment by kwladyka** [comment]
@bretthoerner 
I saved `read-payload.py` and run `netcat -l 9999 | python2 read-payload.py`.
Set DSN to `"http://foo:bar@localhost:9999/1?async=false"`.

I have error:
`[nREPL-worker-1] WARN io.sentry.connection.AbstractConnection - An exception due to the connection occurred, a lockdown will be initiated.
io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.`
`Caused by: java.net.ConnectException: Connection refused (Connection refused)`.

Any idea why?

**Comment by kwladyka** [comment]
@bretthoerner I can confirm it is event X (right event), not event Y (wrong event).

**Comment by bretthoerner** [comment]
Can you link me to the issue on sentry.io?

**Comment by kwladyka** [comment]
https://sentry.io/kwladyka/etingroup-golem/issues/474314673/?referrer=slack

**Comment by bretthoerner** [comment]
Hmm, what are the fingerprints of the event you expect to see and the event you do see?

**Comment by kwladyka** [comment]
The same fingerprint for both X and Y.
```
 "fingerprint": [
    "orders atom -> wfirma",
    "etingroup.sync"
  ]
```
Hmm it seems to work now. Did you change something?

Also I think when I was trying before with different fingerprint I was added correctly.

**Comment by kwladyka** [comment]
I can confirm it changed on localhost and on production (where I didn't touch anything for sure, even not restart the app). Now it works.

Please let me know if you fix something or magic happen :)

**Comment by bretthoerner** [comment]
No changes on my end, very odd.

**Comment by kwladyka** [comment]
Maybe somebody else changing something on sentry.io or something stuck for a while. No idea.
I close the issue. I can't provide any more details.

**Comment by kwladyka** [comment]
It is happening again with different event :(

What is funny I discover something is wrong first time only, because I send the same error to Sentry and Slack.
```
(when-not wfirma-fail?
          (slack/send-danger error-info))
        (throw
          (ex-info "wfirma API" error-info))
```

Today I am trying to find `3de6efe8c7564fbe86a489d3c8de7ae8` and it is the same situation like yesterday.

I am thinking today I send event to Senry and for some reason Sentry doesn't add it to events. Instead report on slack last known issue. It looks like that.

I see in "Events" in issue what I linked only 1 event today. While app sent about 21 and slack bot reported that number of messages.

Can I provide more useful information?

**Comment by kwladyka** [comment]
<img width="41" alt="image" src="https://user-images.githubusercontent.com/3903726/52477619-dfbe5580-2ba2-11e9-85e9-a7d30aef48a2.png">
What this mean in "USER" column? I see it since 28-01-2019. Before it was `-`.
Maybe it is connected in some way. Any update on Sentry close to this date?

**Comment by bretthoerner** [comment]
Can you link me to an event that shows that?

**Comment by kwladyka** [comment]
Check link to issue, which I paste before. All events since this day have it.
For example: https://sentry.io/kwladyka/etingroup-golem/issues/474314673/events/45495044805/

I am trying update things now, so at least to that moment.

**Comment by bretthoerner** [comment]
Oh, that's just a placeholder for an avatar. Yours don't have them since you're using IP but if you sent an email or username they could.

So `3de6efe8c7564fbe86a489d3c8de7ae8` is an Event ID you manually set when you sent the event to Sentry? Or logged after you sent it?

The underlying Java SDK uses SLF4J (log4j, logback, whatever implementation you use). Have you tried enabling DEBUG logging (at least for Sentry) to be totally sure the event makes it to Sentry with no error?

**Comment by kwladyka** [comment]
I don't set event ID myself. It is what `(sentry/send-event ...)` return.
No. Not sure how to debug it so deeply.

I use `[org.slf4j/slf4j-simple "1.7.25"]`.

Are you able to check (read full log) events which sentry.io get today form my app? It will be the easiest way to verify everything.

**Comment by bretthoerner** [comment]
Oh, is this a free account? I think this has to do with event sampling, where we keep the analytical data (like counts) but don't keep the event.

**Comment by bretthoerner** [comment]
I found your event in our stats DB but not our raw event storage:

https://github.com/getsentry/sentry/blob/727ff41313ae8ecae5a1b514385295050f8d2864/src/sentry/event_manager.py#L149-L158

https://github.com/getsentry/sentry/blob/727ff41313ae8ecae5a1b514385295050f8d2864/src/sentry/event_manager.py#L1360-L1366

I need to track down when/why sampling is enabled for an account but I think it's on for free ones and not on for paid.

**Comment by kwladyka** [comment]
Yes, this one is free account.
Am I understand it?
When account is free sentry.io doesn't store events? If I will pay it will store events. When click on Slack bot link it will provide me to right event. Now it open last one event, not the one which it should.

So on the end maybe it is slack bot bug.

I don't see any way to see what exception happen on free account then. It is not useful in any way then. I only know something happen, but no idea what really happen then.

Am I right?

**Comment by bretthoerner** [comment]
Only a percent of events are sampled, when they are sampled the counts still go up (such as total number of events for that issue, tag counts and percentages, graphs, etc) but the event itself is not stored.

You are correct that paid accounts won't sample events.

**Comment by kwladyka** [comment]
So on the end: how can I know what exception happen in app?

Should I make issue in slack bot for sentry? It make a link to the issue, but not to the event which really happen.

I only want to know what exceptions and when occur in the app. How can I achieve it? As I understand it is not possible with free account. Am I right?

Also as I understand if I will pay for "team" account then I will be able to see exceptions, which happen.

**Comment by bretthoerner** [comment]
If anything I think this would be an issue in the Sentry repo, where we need to make notifications (in general) note that the event was sampled and we're only pointing to the general issue.

I think our default is to only send a notification if the issue is new or if it is a regression. And we never sample in those cases:

https://github.com/getsentry/sentry/blob/b971f2bfd1912632db8cbabdbb07dcf942590d09/src/sentry/event_manager.py#L1379-L1380

You must have your account set to notify you on every single event. If you marked your issue as resolved and it "came back" the event would not be sampled. I think it's uncommon for users to want to hear about every single *event*, what they want to hear about is a new *issue* (a single grouping of the event).

And yes, paid accounts aren't sampled.

**Comment by kwladyka** [comment]
Alert rules
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/3903726/52493667-5ae83180-2bcc-11e9-883b-49ed0449711c.png">

> I think it's uncommon for users to want to hear about every single _event_, what they want to hear about is a new _issue_ (a single grouping of the event).

Hmm maybe I miss the idea of Sentry, but I though one of the purpose is to monitor the app errors to react on them. For that purpose knowledge about exceptions in "real time" is on the first place. But maybe I miss the concept and it is more statistical tool, than monitoring. Hmm.
