### ISSUE TITLE
Filtering events with beforeSend

### ISSUE THREAD

**Issue by akotek** [getsentry/sentry-clj#26]
Would be helpful if there will be any support to filter events (i.e based on Environment or some any other removal), this is supported in the Java SDK with [beforeSend](https://docs.sentry.io/platforms/java/configuration/filtering/#using-beforesend), and can be added to the `sentry/init!` method..

**Comment by dharrigan** [comment]
Release https://github.com/getsentry/sentry-clj/releases/tag/3.1.135 introduces a `before-send-fn` into the initialisation map to allow for events to be changed before sending (and even filtered out if need be)
