### ISSUE TITLE
Outdated dependency on the Java client

### ISSUE THREAD

**Issue by onetom** [getsentry/sentry-clj#30]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Clojure v5.0.149

### Steps to Reproduce

Report an exception as documented.

### Expected Result

No "warning" about Sentry client update at the bottom of the https://sentry.io/organizations/<org>/issues/<issue-id>/?project=<project-id> page

### Actual Result

I'm seeing a Sentry client update messge on the website:
> We recommend you update your SDK from @v5.0.1 to @v5.1.0 (All sentry packages should be updated and their versions should match)

**Comment by dharrigan** [comment]
Hi @onetom Thank you for your message. This should be fixed in the release about to go out :-)

**Comment by dharrigan** [comment]
Hi,

Fixed now on latest release: https://github.com/getsentry/sentry-clj/releases/tag/5.0.151.

Enjoy!
