### ISSUE TITLE
performance monitoring support 

### ISSUE THREAD

**Issue by olymk2** [getsentry/sentry-clj#32]
Is the performance monitoring supported seems this is based on the java library https://docs.sentry.io/platforms/java/performance/ the setting are not listed in the readme how ever.

**Comment by dharrigan** [comment]
Hi,

Thank you for your comment. That is indeed very interesting. Would you have an example of how this might work? Thank you.

**Comment by olymk2** [comment]
nope figured that's your department I was hoping to just try it out on an app I don't know much about it really only what I read so hoped to enable i and see what it can do
