### ISSUE TITLE
Update to sentry-java 6.x

### ISSUE THREAD

**Issue by antonmos** [getsentry/sentry-clj#48]
Hello!
Any plans to update to sentry-java 6.x?

thanks!

**Comment by dharrigan** [comment]
Hey!

Yes, totally. I've been waiting until the 6.X release has calmed down a bit. Looks like it has! I'll be putting some effort in the next couple of weeks to perform an update!

-=david=-

**Comment by dharrigan** [comment]
I've done the initial pass now of upgrading to 6.3.X. All tests pass.
