### ISSUE TITLE
I have no idea what `message.formatted` means

### ISSUE THREAD

**Issue by boxxxie** [getsentry/sentry-clj#49]
> :formatted - A String containing the fully formatted message. If missing, Sentry will try to interpolate the message.

so far, i can't find an example of this, other than incorrect documentation from sentry's docs that are linked to on this README.

https://develop.sentry.dev/sdk/event-payloads/message/

the incorrect part is the `required` label, which is completely contradicted in the description of that field.

is this supposed to be json with indenting?
can i only have this field and none of the other fields? `message` `params`?
should i use all of the fields?
what should the params fields contain?
i'm only asking because the documentation is unreliable. 

example from the docs, which don't really help me understand how i should make my messages.
```
{
  "message": {
    "message": "My raw message with interpreted strings like %s",
    "params": ["this"]
  }
}
```

**Comment by boxxxie** [comment]
it seems like this message is supposed to do stuff that is way too fancy.

in `map->event`
`updated-message (if (string? message) {:message message} message)`
i think this line is incorrect, and should be `{:formatted message}`

I think my main issue is i'm trying to figure out how to get the UI or API accepting my data, and i'm just doing an awful lot of trial and error. it's really hard to tell, even from reading the code, how i'm supposed to use the API (including java API where all the java docs are pretty much empty).

i think what i want (to do my own json encoder) is not supported, from issues i've seen in the java API, and i can't tell if i can give a json string to any java methods based on the docs.

i guess i can't really fault this library for missing stuff or being hard to understand, because the java sdk and lack of documentation in general, seems like the root of this issue.

off topic: 
i think `(str (Sentry/captureEvent (map->event event)))` is not good design in this case, as a user of this lib, i want to be able to access the java parts so i can fill in the gaps.

`map->event` should be public

**Comment by bago2k4** [comment]
I agree with you on serval points @boxxxie but not on the change you are suggesting about `updated-message`.

```
updated-message (if (string? message) {:message message} message)
```

That line is correct since `map-event` expect `message` to be a map and not a string, so that line is used to make sure message has the right type.

Why you would want to replace `message` with `formatted`?
they are used in different ways in `map->event` as you can see at lines 103 and 104 of core.clj. Also if you replace that line with just `{:formatted message}` you are not going to use the passed `formatted` value anyway, you just override it with another value which is not formatted by definition

**Comment by boxxxie** [comment]
I don't have this issues anymore. i have started using the rust SDK now.
i've found the actual documentation https://develop.sentry.dev/sdk/event-payloads/types and json schema for sentry. so, all of my payloads are validated against the official schema now. 

i have a new problem, but it's not related to this. i don't think there are any SDKs that respect the official documentation. 

anyway, in the next few days i'm going to give the rust guys about 100 edge case errors for them to fix up :)

**Comment by bago2k4** [comment]
Yeah, I love sentry but I have to say some of these sdk need some work at least to make them consistent with the documentation and the README examples.
