### ISSUE TITLE
Uncaught handler option documentation does not match code

### ISSUE THREAD

**Issue by sjamaan** [getsentry/sentry-clj#58]
In the [README](https://github.com/getsentry/sentry-clj/blob/f2ebf8f9e043e72088d1c20710d85a96f453ccb4/README.md?plain=1#L71), it says that `:uncaught-handler-enabled` supersedes the deprecated `:enable-uncaught-exception-handler`.

If you look at the changelog, it says for [version 5.5.165](https://github.com/getsentry/sentry-clj/blob/f2ebf8f9e043e72088d1c20710d85a96f453ccb4/CHANGELOG.md#55165):
> Deprecated enable-uncaught-exception-handler and added uncaught-handler-enabled to improve naming consistency with Java SDK.

but then for version [6.13.191](https://github.com/getsentry/sentry-clj/blob/f2ebf8f9e043e72088d1c20710d85a96f453ccb4/CHANGELOG.md#613191) it says:
> Remove uncaught-handler-enabled as it's been removed from the Java SDK
>
> *  Use enable-uncaught-exception-handler instead

And indeed, in [this commit](https://github.com/getsentry/sentry-clj/commit/264880039b3e8edb2890b6030bd6a7c4c3aaf39b) `enable-uncaught-exception-handler` was deprecated in favor of `uncaught-handler-enabled`. However, it was never officially "undeprecated" and in [this commit](https://github.com/getsentry/sentry-clj/commit/3268ea3062384584c07b31526e8a5aa2db4ae546) the newer (favored) option `uncaught-handler-enabled` was unceremoniously removed and replaced with the old (supposedly deprecated) option.

So it's a bit unclear what the intention is. From where I'm standing, it looks like some back-and-forth deliberation was done and eventually the decision was made that the deprecation and the new name didn't make sense and essentially rolled back to the pre-deprecation situation.

If that's indeed the situation and this is as intended, please update the `README` to correctly reflect the fact that `:uncaught-handler-enabled` doesn't actually do anything (i.e. remove mentions of it), and that `:enable-uncaught-exception-handler` should be used (i.e., remove the sentence that says it's deprecated).

**Comment by DerGuteMoritz** [comment]
This also tripped me up, would appreciate clarification :pray:
