### ISSUE TITLE
In-app frames should be a default option on a DSN unless specified otherwise

### ISSUE THREAD

**Issue by devn** [getsentry/sentry-clj#6]
Frames from clojure app namespaces should be tagged as in-app without a user needing to know about passing them on the DSN as an option.

**Comment by bretthoerner** [comment]
Dumb question: how do I know what `ns` are the user's app? I don't think the clojure stdlib or other libraries should be labeled in-app.

**Comment by devn** [comment]
@bretthoerner You don't, unfortunately. I guess my suggestion would be to strongly direct users to set their app's namespace(s) on the DSN in the README, noting that `their-app` should be `their_app`.

**Comment by dharrigan** [comment]
Hi!

I'm helping to look after this project. Given that a new release is out now, version 3.1.0, and given that this ticket is +3 years old, I am going to close it. If you feel that this is still an issue now, please can you add a new issue with as much information as possible.

Thank you.

-=david=-
