### ISSUE TITLE
Before/after context source

### ISSUE THREAD

**Issue by devn** [getsentry/sentry-clj#7]
The only way I've seen fit to add source context was to do a healthy bit of hackery. Could there be a better default way of providing this information?

**Comment by bretthoerner** [comment]
I think we'll have to do hackery, but we should do it *in* the SDK and add caching.

Posting your gist for posterity: https://gist.github.com/devn/86c41cec28afc4f8e02fcc3a77b6a2f4

**Comment by devn** [comment]
@bretthoerner Someone on the Clojure Slack channel showed me an improved version. Generally speaking, it's worth looking at https://github.com/sethtrain/raven-clj/network, namely hcarvalhoalves fork, but I see some commits that may be of interest on other forks.

**Comment by dharrigan** [comment]
Hi!

I'm helping to look after this project. Given that a new release is out now, version 3.1.0, and given that this ticket is +3 years old, I am going to close it. If you feel that this is still an issue now, please can you add a new issue with as much information as possible.

Thank you.

-=david=-
